#!/bin/bash


: '
TODO:

add error handling

after the command line tool is done
	- add I/O combinators
	- try out infinite loops
	- try fib w/o Y combinator 
	- check typability of terms in lambda or sk? mark them and only run if nothing else available


'

fileExists() {
	
	if [ -z "$1" ]; then
		printf "Error: source file not specified.\n"
		return 1
	elif [ -f "$1" ]; then
		return 0
	else 
		printf "Error: ${1} could not be found.\n"
		return 1
	fi
	
}

fileGiven() {
	if [ -z "$1" ]; then
		printf "Error: target file not specified.\n"
		return 1
	else
		return 0
	fi
}	

compile() {
	#create .sk file
	./conv "$1" temp.sk
	#create C header file containing the .sk file's data in an array
	xxd -i temp.sk > temp.h
	#compile runc, which is linked to temp.h
	gcc -g runc.c -o "$2"
	#remove unecessary files
	rm temp.sk
	rm temp.h
}

runCommand() {

	if [ "$1" = "help" ]; then 
		printf "help                                        list all commands\n"
		printf "build                                       generate the lexer, parser, and compiler\n"
		printf "interpret [sourceFile] [targetFile]         store the combinatory representation of [sourceFile] at [targetFile]\n"
		printf "compile [sourceFile] [targetFile]           compile [sourceFile] into an executable program stored at [targetFile]\n"
		printf "run [fileName]                              compile [sourceFile] and run the program\n"
		printf "quit                                        exit command line tool\n"
		
	elif [ "$1" = "build" ]; then
		alex lexer.x
		happy parser.y
		ghc -no-keep-hi-files -no-keep-o-files -main-is Conv conv.hs
		
	elif [ "$1" = "interpret" ]; then
		
		if fileExists "$2" && fileGiven "$3"; then
			./conv "$2" "$3"
			printf "%s successfully compiled to %s" "$2" "$3"
		fi
		
		
		
	elif [ "$1" = "compile" ]; then
		if fileExists "$2" && fileGiven "$3"; then
			compile "$2" "$3"
			printf "%s successfully compiled to %s" "$2" "$3"
		fi
		
	elif [ "$1" = "run" ]; then 
		if fileExists "$2"; then
			compile "$2" temp.exe
			./temp.exe
			rm temp.exe
		fi
		
		
	else
		printf "Command not recognised. Try running 'help' to see a list of commands.\n"
	fi

}

mainLoop() {
	if [ -z "$1" ]; then
		printf "Welcome to the lambda compiler command line tool!\nTry running 'help' to see a list of commands.\n"
		while true; do
			printf ">>> "
			read -r command source target
			
			if [ "$command" = "quit" ]; then
				break
			fi
			
			runCommand "$command" "$source" "$target"
			printf "\n"
		done
	else 
		runCommand "$1" "$2" "$3"
	fi
		
}

mainLoop "$1" "$2" "$3"