#!/bin/bash

#check if the user has specified a file, and if it exists
fileExists() {
	
	if [ -z "$1" ]; then
		printf "Error: source file not specified.\n"
		return 1
	elif [ -f "$1" ]; then
		return 0
	else 
		printf "Error: ${1} could not be found.\n"
		return 1
	fi
	
}

#check if the user has specified a file
fileGiven() {
	if [ -z "$1" ]; then
		printf "Error: target file not specified.\n"
		return 1
	else
		return 0
	fi
}	

#create executable file from program
compile() {
	#create .sk file
	./conv "$1" temp.sk || return 1
	#create C header file containing the .sk file's data in an array
	xxd -i temp.sk > temp.h || return 1
	#compile runc, which is linked to temp.h
	gcc -g runc.c -o "$2" || return 1
	#remove unecessary files
	rm temp.sk
	rm temp.h
}

#run a single command
runCommand() {

	if [ "$1" = "help" ]; then 
		printf "help                                        list all commands\n"
		printf "build                                       generate the lexer, parser, and compiler\n"
		printf "interpret [sourceFile] [targetFile]         store the combinatory representation of [sourceFile] at [targetFile]\n"
		printf "compile [sourceFile] [targetFile]           compile [sourceFile] into an executable program stored at [targetFile]\n"
		printf "run [sourceFile]                            compile [sourceFile] and run the program\n"
		printf "debug [sourceFile]                          compile [sourceFile] and run the program with GDB\n"
		printf "quit                                        exit command line tool\n"
		
	elif [ "$1" = "build" ]; then
		#generate lexer, parser, and compiler
		alex lexer.x && happy parser.y && ghc -no-keep-hi-files -no-keep-o-files -main-is Conv conv.hs
		
		if [ $? -eq 0 ]; then 
			printf "Build command succeeded."
		else 
			printf "Build command failed. Please check that you have alex, happy, and ghc."
		fi
		
	elif [ "$1" = "interpret" ]; then
		#create SK file from input
		
		if fileExists "$2" && fileGiven "$3"; then
			./conv "$2" "$3"
			
			if [ $? -eq 0 ]; then
				printf "%s successfully compiled to %s" "$2" "$3"
			else
				printf "Compilation failed."
			fi
		fi
		
		
		
	elif [ "$1" = "compile" ]; then
		#create executable file from input
		
		if fileExists "$2" && fileGiven "$3"; then
			compile "$2" "$3"
			
			if [ $? -eq 0 ]; then
				printf "%s successfully compiled to %s" "$2" "$3"
			else
				printf "Compilation failed."
			fi
		fi
		
	elif [ "$1" = "run" ]; then 
		#create executable file from input, run it, and delete it
		
		if fileExists "$2"; then
			compile "$2" temp.exe	
				
			if [ $? -eq 0 ]; then
				printf "Compilation successful. Running program...\n"
				./temp.exe
				rm temp.exe
			else
				printf "Compilation failed."
			fi
			
		fi
	
	elif [ "$1" = "debug" ]; then
		#create executable file from input, run it with gdb, and delete it
		
		if fileExists "$2"; then
			compile "$2" temp.exe	
				
			if [ $? -eq 0 ]; then
				printf "Compilation successful. Starting gdb...\n"
				gdb ./temp.exe
				rm temp.exe
			else
				printf "Compilation failed."
			fi
			
		fi
		
	else
		printf "Command not recognised. Try running 'help' to see a list of commands.\n"
	fi

}

#main script loop
mainLoop() {
	if [ -z "$1" ]; then
		#if the user hasn't specified a command when calling lambda, enter the command line tool
		
		printf "Welcome to the lambda compiler command line tool!\nTry running 'help' to see a list of commands. Please run the 'build' command before first use.\n"
		while true; do
			printf ">>> "
			read -r command source target
			
			if [ "$command" = "quit" ]; then
				break
			fi
			
			runCommand "$command" "$source" "$target"
			printf "\n"
		done
		
	else 
		#otherwise, only run the command the user has specified
		runCommand "$1" "$2" "$3"
	fi
		
}

mainLoop "$1" "$2" "$3"